import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../services/pdf_download.dart';
import 'sop_draft.dart';

/// Builds and saves a downloadable PDF for an [SopDraft].
///
/// Reuses the existing platform-aware `savePdf` helper so the same
/// download/share flow works on native (Printing.sharePdf) and web
/// (blob anchor) without new dependencies.
class SopPdfBuilder {
  const SopPdfBuilder();

  /// Builds the PDF bytes for the supplied draft. Useful for tests and
  /// preview flows.
  Future<Uint8List> buildPdfBytes(SopDraft draft) async {
    final document = pw.Document(
      title: draft.title,
      author: 'ScholarBird AI Hub',
      subject: 'Statement of Purpose',
    );

    final theme = pw.ThemeData.withFont(
      base: pw.Font.times(),
      bold: pw.Font.timesBold(),
      italic: pw.Font.timesItalic(),
    );

    document.addPage(
      pw.MultiPage(
        theme: theme,
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(48, 56, 48, 56),
        header: (context) => _header(context, draft),
        footer: (context) => _footer(context),
        build: (context) => _buildBody(draft),
      ),
    );

    return document.save();
  }

  /// Builds the PDF and hands the bytes to the platform-specific saver.
  Future<void> downloadSop(SopDraft draft) async {
    final bytes = await buildPdfBytes(draft);
    await savePdf(bytes, draft.suggestedFilename());
  }

  pw.Widget _header(pw.Context context, SopDraft draft) {
    final dateLabel = DateFormat.yMMMd().format(draft.createdAt);
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 12),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  draft.title,
                  style: pw.TextStyle(
                    fontSize: 14,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                if (draft.subtitle.isNotEmpty)
                  pw.Text(
                    draft.subtitle,
                    style: const pw.TextStyle(
                      fontSize: 9,
                      color: PdfColors.grey700,
                    ),
                  ),
              ],
            ),
          ),
          pw.Text(
            dateLabel,
            style: const pw.TextStyle(
              fontSize: 9,
              color: PdfColors.grey700,
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _footer(pw.Context context) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(top: 8),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Generated by ScholarBird AI Hub',
            style: const pw.TextStyle(
              fontSize: 8,
              color: PdfColors.grey600,
            ),
          ),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: const pw.TextStyle(
              fontSize: 8,
              color: PdfColors.grey600,
            ),
          ),
        ],
      ),
    );
  }

  List<pw.Widget> _buildBody(SopDraft draft) {
    final widgets = <pw.Widget>[];

    // Programme / scholarship summary block
    final meta = <String>[
      if (draft.targetProgramme.trim().isNotEmpty)
        draft.targetProgramme.trim(),
      if (draft.targetUniversity.trim().isNotEmpty)
        draft.targetUniversity.trim(),
      if (draft.targetField.trim().isNotEmpty) draft.targetField.trim(),
      if (draft.scholarshipName.trim().isNotEmpty)
        'Specific scholarship: ${draft.scholarshipName.trim()}',
    ];
    if (meta.isNotEmpty) {
      widgets.add(
        pw.Container(
          padding: const pw.EdgeInsets.symmetric(vertical: 6, horizontal: 10),
          margin: const pw.EdgeInsets.only(bottom: 16),
          decoration: pw.BoxDecoration(
            color: PdfColors.grey100,
            borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
          ),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'Application summary',
                style: pw.TextStyle(
                  fontSize: 10,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.grey800,
                ),
              ),
              pw.SizedBox(height: 2),
              pw.Text(
                meta.join('\n'),
                style: const pw.TextStyle(fontSize: 10),
              ),
            ],
          ),
        ),
      );
    }

    // Body paragraphs
    final paragraphs = draft.body
        .split(RegExp(r'\n\s*\n'))
        .map((p) => p.trim())
        .where((p) => p.isNotEmpty)
        .toList();
    for (final paragraph in paragraphs) {
      widgets.add(
        pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 10),
          child: pw.Text(
            paragraph,
            style: const pw.TextStyle(
              fontSize: 11,
              lineSpacing: 3,
            ),
          ),
        ),
      );
    }

    // Footnote when the draft flagged missing fields
    if (draft.missingFields.isNotEmpty) {
      widgets.add(
        pw.SizedBox(height: 12),
      );
      widgets.add(
        pw.Container(
          padding: const pw.EdgeInsets.all(8),
          decoration: pw.BoxDecoration(
            color: PdfColors.amber50,
            borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
          ),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'Notes for the applicant',
                style: pw.TextStyle(
                  fontSize: 10,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.amber800,
                ),
              ),
              pw.SizedBox(height: 2),
              pw.Text(
                'Reviewer flagged these gaps: ${draft.missingFields.join(', ')}. '
                'Consider adding them before submitting.',
                style: const pw.TextStyle(fontSize: 9),
              ),
            ],
          ),
        ),
      );
    }

    return widgets;
  }
}
